### ISSUE TITLE
Internationalisation and customisation of greeting

### ISSUE THREAD

**Issue by almereyda** [bost-ty/firefox-lucid#10]
The greeting is currently talking in English to me. Possibly I would like it to greet me in any of the other languages of the world. And since lucid already knows about the time of the day, and adjusts its greeting to me, maybe I'd also want it to say different, customisable mantras depending on the daytime.

Technically speaking, I'm asking if there is interest of starting an internationalisation project for `ff-lucid`, in which we:

- add or recognise regional settings and adapt the time string as well as the language of the greeting to the locale.
- use this infrastructure of being able to replace the text strings based on (language-specific) templates to also override them with custom preferences.

**Comment by bost-ty** [comment]
This is a great request; Daniel Eden added a starting point for localization but as far as I know he hasn't taken it further in the Chrome version of the extension.

I'm not familiar with any processes of adding multiple languages/localization/internationalization (sorry I use z and not s for those words 😄), but I think it would make a great addition to the extension.


> add or recognise regional settings and adapt the time string as well as the language of the greeting to the locale.

Yes! I would also add a "language select" option to the options menu to override this option or provide a backup in case they have privacy settings that block detection of regional/language settings (possible in Firefox, to my knowledge).

> use this infrastructure of being able to replace the text strings based on (language-specific) templates to also override them with custom preferences.

Yes! This may tie-in with the "language select" option; a "custom greeting" option that overrides the default string, but still uses the localized language with placeholder variables such as `{timeOfDay}` to insert variables in the user's desired string.


I really like your idea of adding different greetings/mantras depending on the time of day. That would probably be another piece of configuration to the two points above.

@almereyda , are you interested in providing a pull request to start on this new feature? I don't personally have experience or even an idea of how to begin adding support for other languages (that's a personal failing for me).

**Comment by almereyda** [comment]
Yes, that sounds like something that I could do. I would have to wrap my head around this by figuring out the next step from where I am now. This means a verbose conversation with myself about the impeding changes in this issue, and from a certain point in time also in a PR.

Further on we may also want to consider sharing these developments with the codebase targeting the Chromium platform at `upstream`.

Let me get back to this when I am ready, which realistically can be within a week or half a year, and focus on taking the steps in the right sequence, and not their implementation velocity. Let's optimise for throughput, and not for latency.

¹ 

* [Slow Technology ⸰ Slow Ideas](http://jon.federated.wiki/view/slow-technology/view/slow-ideas/view/slow-hunch)
    * [Via: Zerubavel-1987-The-Language-of-Time-Toward-a-Semiotics-of-Temporality.pdf](https://via.hypothes.is/http://wendynorris.com/wp-content/uploads/2018/07/Zerubavel-1987-The-Language-of-Time-Toward-a-Semiotics-of-Temporality.pdf)
    * [Via: Pschetz-Bastian-Speed-2016-Temporal-design-Looking-at-time-as-social-coordination.pdf](https://via.hypothes.is/http://wendynorris.com/wp-content/uploads/2018/07/Pschetz-Bastian-Speed-2016-Temporal-design-Looking-at-time-as-social-coordination.pdf)
* [I Am Slow And That's Okay - Steven Hicks](https://www.stevenhicks.me/blog/2020/10/i-am-slow-and-thats-okay/)

**Comment by bost-ty** [comment]
Labeled with good first issue: anyone is welcome to translate/internationalize.

We need:
- [ ] Greeting
- [ ] TImes of day
- [ ] Placeholder notepad text
- [ ] Options menu

**Comment by bost-ty** [comment]
Closing this for now as we haven't had any more discussion.
