### ISSUE TITLE
 Where to find history of contents/notes?

### ISSUE THREAD

**Issue by yarub123** [bost-ty/firefox-lucid#11]
Don't see it in preferences or elsewhere? I just added the extension, so maybe it just appends them to the side or the bottom once they're added and a new day starts?

**Comment by bost-ty** [comment]
Hi yarub! Notes have no history -- it's more a scratchpad, which is by design for this extension. There are tools for viewing your Firefox Sync data, which is where the notepad contents are stored, but there is no revision history, only the current Sync state's contents.

**Comment by yarub123** [comment]
@bost-ty Thanks for the response homie. Much appreciated. Yeah I figured later that what I'm asking for goes beyond the purpose. I'm actually glad it doesn't have that option. Simple is always better, imo.
