### ISSUE TITLE
Notepad text do not persist across new tabs

### ISSUE THREAD

**Issue by Hwiet** [bost-ty/firefox-lucid#7]
As the title says. If I type some text on a new tab, close it, and open a new tab again, the new tab does not have the text I've previously typed.

**Comment by bost-ty** [comment]
Hey Kyeu! Thanks for submitting this issue. 

Do you have Firefox Sync enabled & signed in to your account? The extension relies on this to save and update the notepad data. If you don’t, give it a try and let me know how it goes either way. If you do and it isn’t working, we can take further troubleshooting steps to get this working.

**Comment by Hwiet** [comment]
Yes. In fact, I've just created a Firefox account and synced it yesterday, but the behavior of the add-on did not change.

**Comment by bost-ty** [comment]
Issue appears to be linked to same cause as #6. Linking and closing -- thank you!
